[[redirects]]
from = "/polka"
to = "/countdown"
status = 302
force = true

[[redirects]]
from = "/polka/*"
to = "/countdown"
status = 302
force = true

[[redirects]]
from = "/botan"
to = "/countdown"
status = 302
force = true

[[redirects]]
from = "/botan/*"
to = "/countdown"
status = 302
force = true