[[redirects]]
from = "/2021/polka/*"
to = "/2021/polka/index.html"
status = 200

[[redirects]]
from = "/2021/botan/*"
to = "/2021/botan/index.html"
status = 200

[[redirects]]
from = "/2022/nene/*"
to = "/2022/nene/index.html"
status = 200

[[redirects]]
from = "/2022/botan/*"
to = "/2022/botan/index.html"
status = 200
