[[redirects]]
from = "/nene"
to = "/"
status = 302
force = true

[[redirects]]
from = "/polka"
to = "/"
status = 302
force = true

[[redirects]]
from = "/lamy"
to = "/"
status = 302
force = true

[[redirects]]
from = "/botan"
to = "/"
status = 302
force = true