[[redirects]]
from = "/nene/*"
to = "/2021/nene/"
status = 200

[[redirects]]
from = "/polka/*"
to = "/2021/polka/"
status = 200

[[redirects]]
from = "/lamy/*"
to = "/2021/lamy/"
status = 200

[[redirects]]
from = "/botan/*"
to = "/2021/botan/"
status = 200

[[redirects]]
from = "/2021/polka/*"
to = "/2021/polka/index.html"
status = 200

[[redirects]]
from = "/2021/botan/*"
to = "/2021/botan/index.html"
status = 200

[[redirects]]
from = "/2022/nene/*"
to = "/2022/nene/index.html"
status = 200

[[redirects]]
from = "/2022/polka/*"
to = "/2022/polka/index.html"
status = 200

[[redirects]]
from = "/2022/botan/*"
to = "/2022/botan/index.html"
status = 200
